name: Evinroment Variables

on:
  push:
    branches:
      - main

env:
  WF_ENV: Available to all JOBS

jobs:
  log-env: 
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to all steps in log-env job
    steps:
      - name: Log ENV Variables
        env:
          STEP_ENV: available to only this step
        run: |
          echo ${{ env.WF_ENV }}
          echo ${{ env.JOB_ENV }}
          echo ${{ env.STEP_ENV }}
      - name: Log ENV V2
        run: |
          echo ${{ env.WF_ENV }}
          echo ${{ env.JOB_ENV }}
          echo ${{ env.STEP_ENV }}
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log Default 
        run: |
          echo "GITHUB_WORKFLOW  ${{ github.workflow }}"
          echo "GITHUB_ACTION  ${{ github.action }}"
          echo "GITHUB_ACTIONS  ${{ github.actions }}"
          echo "GITHUB_ACTOR  ${{ github.actor }}"
          echo "GITHUB_REPOSITORY  ${{ github.repository }}"
          echo "GITHUB_EVENT_NAME  ${{ github.event_name }}"
          echo "GITHUB_WORKSPACE  ${{ github.workspace }}"
          echo "GITHUB_SHA  ${GITHUB_SHA}"
          echo "GITHUB_REF  ${{ github.ref }}"
          echo "WF_ENV: ${{ env.WF_ENV }}"
          echo "JOB_ENV: ${{ env.JOB_ENV }}"
          echo "STEP_ENV: ${{ env.STEP_ENV }}"
          
          
          
          
